# Github Workflow for CI
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2

          - name: Setup Node.js 19.x
            uses: actions/setup-node@v1
            with:
              node-version: 19.x

          - name: Build Docker Image
            run: yarn image:build
